### ISSUE TITLE
平方根の計算方法

### ISSUE THREAD

**Issue by kei319** [Satachito/SliP#4]
平方根の計算はどうやりますか？

**Comment by Satachito** [comment]
sqrt でできます。ちなみに三乗根は cbrt、他の超越関数は下を見てください。
https://github.com/Satachito/SliP/blob/main/Sugared.Math.slip
名前は JavaScript に合わせてあります。
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Math
